[project]
name = "apoc-data"
version = "0.1.3"
description = "Data from the Alaska Public Offices Commission."
authors = [
    {name = "Nick Crews", email = "nicholas.b.crews@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
apoc-data = "apoc_data.cli:main"

[project.optional-dependencies]
scrape = [
    "playwright",
]

[dependency-groups]
dev = [
    "apoc-data[scrape]",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"
