name: Scrape and Release

on:
  schedule:
    # Every week
    # 10:47 AM UTC every day (3:47 AM pacific time)
    # There should be little APOC filing activity and low load on githubs servers.
    - cron: "47 10 * * *"
  workflow_dispatch:

jobs:
  scrape_and_release:
    name: Run and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install pdm
        run: python -m pip install pdm
      - name: Create dev environment
        run: pdm install
      - name: Install Chromium for Playwright
        run: pdm run playwright install chromium
      - name: Scrape Data
        run: pdm run python -m apoc_data.scrape --directory scraped

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/release.sh
