name: Scrape and Release

on:
  schedule:
    # Every week
    # 10:47 AM UTC every day (3:47 AM pacific time)
    # There should be little APOC filing activity and low load on githubs servers.
    - cron: "47 10 * * *"
  workflow_dispatch:

# Needed for creating releases.
permissions:
  contents: write

jobs:
  scrape_and_release:
    name: Scrape and Upload Release
    runs-on: ubuntu-latest
    # A healthy run takes ~30 min, but some runs in election season 2026 were taking 90.
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Scrape Data
        run: uv run apoc-data scrape --directory scraped --attempts 6 --retry-backoff 8

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/release.sh
